### PR TITLE
Insert-tips-page-content

### LINKED ISSUE #14: Decide the content for "Tips"
## Description
Add the section about Health remedies and write in it what could be the possible things which should be followed. 
Also a section for Medicine to be taken during the period for pain. 

## To get merged
Discussed with at least one mentor

### PR DESCRIPTION
**Pull request by Nidhikamewar15**
Issue FIXES #14 
I have inserted the content in the tips page of the website.

pic1
pic2

### CODE REVIEW

**Comment by khushishikhu** [comment]
@Nidhikamewar15 I liked your content. Thank you so much for this PR. Also when the user click on Read More button make the user directs it to that particular content on the internet. I hope you are clear what I want to convey you?

**Comment by Nidhikamewar15** [comment]
Sure @khushishikhu

**Comment by Nidhikamewar15** [comment]
I have added the links to the relevant websites in the "Read More" buttons. 
@khushishikhu Please review it.

**Comment by khushishikhu** [comment]
@Nidhikamewar15 LGTM 💯  Thank You so much for your contribution. We liked your work. keep contributing.

**Review by khushishikhu — APPROVED** [review]
@Nidhikamewar15 LGTM 💯  Thank you so much for contribution. We appreciate your efforts.

**Pull request merged**
