### PR TITLE
Added range feature in calendar

### PR DESCRIPTION
**Pull request by sayna3311**
Modified the calendar. Added the feature, which allows users to choose a range of dates, accordingly.
Solving issue #8

### CODE REVIEW

**Comment by khushishikhu** [comment]
@sayna3311 I have tested this PR. It is throwing some errors can you please look for it and try to resolve.
image

**Comment by sayna3311** [comment]
Yeah, first you have to install that module by, 
npm install react-day-picker.

**Comment by khushishikhu** [comment]
@sayna3311 Good Job!! Thank You so much for your contribution.

**Comment by Aaishpra** [comment]
Thanks @sayna3311 for your contribution

**Pull request merged**
