### PR TITLE
Display a dialogbox for confirmation

### LINKED ISSUE #66: coding: Display a dailog box
## Is your feature request related to a problem? Please describe.
When a user click on next button on the Calendar page. Display a Dailog box for confirmation. If the want to move on the next page or not

### PR DESCRIPTION
**Pull request by SandeepKrSuman**
#### Description
fixes #66 

#### Describe the changes you've made
Added a component called "DialogNextButton" which is executed whenever someone clicks on the next button on calendar page.

#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
NA

#### Additional context (OPTIONAL)
- Before : 
before_gif

- After : 
after_gif

#### Test plan (OPTIONAL)
Run the app on local host and navigate to the calendar page to see the changes. Click on next button and a dialog box should appear asking for confirmation.  

#### Checklist
- [x] I have added my name in the contributors list at the end of README.md file.
- [x] My code follows the code style of this project.
- [x] My change does not require a change to the documentation.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.
- [x] The title of my pull request is a short description of the requested changes.
- [x] Open Source Program names(OPTIONAL: If you participated in any open-source program then please mention the program name here) - **GSSOC21**

### CODE REVIEW

**Review by Aaishpra — COMMENTED** [review]
Codewise LGTM, 🎉 will approve and merge after testing.

**Comment by Aaishpra** [comment]
@SandeepKrSuman please resolve the merge conflicts

**Comment by SandeepKrSuman** [comment]
@Aaishpra Hope it is resolved now

**Review by Aaishpra — APPROVED** [review]
LGTM great work 🚀 thanks for your contribution @SandeepKrSuman 
Keep Contributing more to the project!

**Comment by SandeepKrSuman** [comment]
Sure. Thanks a lot.

**Pull request merged**
