### PR TITLE
Adding CSS animation effect to the title of homepage

### LINKED ISSUE #40: Animated Heading
Hello ! I am a Drishti, I am a GSSOC Participant I would like to make the heading "Hi Girls, wanna track your periods!!" more attractive by enhancing its CSS and implement text typing animation effect.
Do assign this issue to me.
Thanks in Advance.

### PR DESCRIPTION
**Pull request by drishtipeshwani**
#### Description
Issue FIXES #40

#### Describe the changes you've made
I had added a typing animation effect to the main title of the homepage.

#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
NA

#### Video attached of the changes made

https://user-images.githubusercontent.com/65016769/110801056-daacc280-82a2-11eb-979c-5de985717fb3.mp4

#### Checklist

- [x] I have added my name in the contributors list at the end of README.md file.
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [x] The title of my pull request is a short description of the requested changes.
- [ ] Open Source Program names(OPTIONAL: If you participated in any open-source program then please mention the program name here)

### CODE REVIEW

**Review by Aaishpra — COMMENTED** [review]
Please attach some screenshots when you do something with UI😉

**Comment by drishtipeshwani** [comment]
> Please attach some screenshots when you do something with UI😉

Sure I will Thankyou

**Comment by drishtipeshwani** [comment]
I have added the video of the changes I have made please go over it

**Review by Aaishpra — APPROVED** [review]
Loved it 😍  Thanks @drishtipeshwani for your contribution

**Comment by Aaishpra** [comment]
@drishtipeshwani can you resolve the merge conflicts, once resolved I will reapprove and merge this.

**Comment by drishtipeshwani** [comment]
In  started.module.css I resolved the conflicts but I am not able to ubderstand the conflicts in yarn.lock file also I dont understand why is that file used can you please help

**Comment by Aaishpra** [comment]
See if this [video](https://youtu.be/JtIX3HJKwfo) helps you. If not ping me I will help you in removing those conflicts.

**Comment by Aaishpra** [comment]
Remove the files from this PR which aren't needed

**Comment by drishtipeshwani** [comment]
Hey @Aaishpra I have resolved the conflicts

**Comment by Aaishpra** [comment]
@drishtipeshwani will test this out and review it when i am free from school work😁

**Review by khushishikhu — APPROVED** [review]

**Comment by khushishikhu** [comment]
@drishtipeshwani can you please just update your fork from the upstream branch. And then send us your work. Because I have tested your PR and found out that the tab here button isn't modified in your fork. I hope you got my point. And the animation looks great 😍

**Comment by drishtipeshwani** [comment]
Hey @khushishikhu I have updated the fork

**Comment by Aaishpra** [comment]
@drishtipeshwani the button is still in the wrong place
image
maybe you need to update your master branch aswell

**Comment by drishtipeshwani** [comment]
Hey !! I updated my master branch and tried resolving the conflict is the error still coming ?

**Comment by Aaishpra** [comment]
Yes, you still have merge conflicts in `yarn.lock`. Please remove them.

**Comment by drishtipeshwani** [comment]
> Yes, you still have merge conflicts in `yarn.lock`. Please remove them.

Done

**Comment by khushishikhu** [comment]
@drishtipeshwani Thank You for your contribution. Keep contributing

**Pull request merged**
