### PR TITLE
Updated Gynac Help changes

### LINKED ISSUE #76: Contact Gynecologist Option
The above option will help user to interact with the gynecologist related to menstrual issues and seek immediate guidance.
I can work on its front end . Can you please assign it to me?

### PR DESCRIPTION
**Pull request by AasthaNautiyal**
#### Description
Issue FIXES #76 

#### Describe the changes you've made
Modified the navigation bar for the inclusion of Gynecologist Help option. Added the contact gynecologist form to help the user enter all basic details about their menstrual issue.
#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
NA

#### Checklist

- [ ] I have added my name in the contributors list at the end of README.md file.
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.
- [x] The title of my pull request is a short description of the requested changes.
- [ ] Open Source Program names(OPTIONAL: If you participated in any open-source program then please mention the program name here)

image
@khushishikhu Hi ! I made the changes and updated .Please check.

### CODE REVIEW

**Comment by AasthaNautiyal** [comment]
Description
Added Contact Gynecologist Option 
Issue#76

Describe the changes you've made
Added components for Gynecologist Help . Modified the navbar to add link to the Gynecologist contact form. 

Describe if there is any unusual behaviour of your code(Write NA if there isn't)
NA
Checklist
[✓] My code follows the code style of this project.
 [✓]My change does not require a change to the documentation.
[✓] I have updated the documentation accordingly.
 [x]I have added tests to cover my changes.
 [✓]All new and existing tests passed.
 [✓]The title of my pull request is a short description of the requested changes.
[x] Open Source Program names(OPTIONAL: If you participated in any open-source program then please mention the program name here)

**Comment by AasthaNautiyal** [comment]
@khushishikhu Do I need to make any changes or it is fine?Please review.Thanks

**Comment by khushishikhu** [comment]
@AasthaNautiyal can you just do something that the form looks more clear so that it will not counter with the background of the page. You can add any light colour with the form so that it will look more clear. Else everything is good I appreciate this💯

**Comment by AasthaNautiyal** [comment]
image
 @khushishikhu  Does this work?

**Comment by AasthaNautiyal** [comment]
@khushishikhu Should I commit these changes?Please check.

**Comment by khushishikhu** [comment]
@AasthaNautiyal yes please do commit these changes

**Comment by AasthaNautiyal** [comment]
@khushishikhu I have committed the changes and resolved the merge conflicts. Please have a look .

**Review by khushishikhu — APPROVED** [review]
@AasthaNautiyal LGTM!! 🎉 Thank you so much for contributing . And I really liked your work. Keep contributing, Hope you learned a lot

**Pull request merged**
