### PR TITLE
Decide the content for Tips page

### PR DESCRIPTION
**Pull request by Nidhikamewar15**
I have added a doc file having the contents for the Tips page. Please have a look.  #14

### CODE REVIEW

**Comment by khushishikhu** [comment]
@Nidhikamewar15 I really appreciate your efforts. I liked the content you have written. we will add this on the page when it is ready or open a new issue for you to work on. Thank you!!

**Comment by khushishikhu** [comment]
@Nidhikamewar15 Noe you can write the content on the Tips page of the website as it is ready now. Please checkout the website by updating your branch

**Comment by Nidhikamewar15** [comment]
Sure @khushishikhu

**Comment by Nidhikamewar15** [comment]
@khushishikhu    Medine section should also be displayed in the form of cards on this "Tips" page ??
Also how many such cards (having tips ) you expect me to add?

**Comment by khushishikhu** [comment]
@Nidhikamewar15  yes It can also be displayed. Minimum 4 cards I need here or it's up to you if you like to add more.

**Pull request closed without merging**
