### PR TITLE
 # issue 202modify the do you wanna share exp prompt

### LINKED ISSUE #202: Enhance and modify "Do you want to share your period experience?" prompt
I think it can be modified more attractively because I think the current one is fine but not creating a good view Tell me how do you feel  else I am ready to modify :) @Aaishpra @khushishikhu 
image

### PR DESCRIPTION
**Pull request by satavshreya**
#### Description
Issue FIXES #202 

#### Describe the changes you've made
made css changes

- [x] I have added my name in the contributors list at the end of README.md file.
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [x] The title of my pull request is a short description of the requested changes.
- [ ] Open Source Program names(OPTIONAL: If you participated in any open-source program then please mention the program name here)

### CODE REVIEW

**Comment by satavshreya** [comment]
@Aaishpra @khushishikhu  let me know abt this

**Comment by satavshreya** [comment]
@Aaishpra @khushishikhu let me know abt this

**Comment by khushishikhu** [comment]
@satavshreya Try not to commit in yarn.lock can revert that change

**Comment by Aaishpra** [comment]
Just unstage the file

**Pull request closed without merging**
