### PR TITLE
Added Emergency Button.

### LINKED ISSUE #78: We can also live live locations of nearest restrooms,washrooms and hospitals in case of any emergency.
## Describe the solution you'd like
I want to provide an additional feature of a map where a user can find washrooms and hospitals nearer to her live locations

### PR DESCRIPTION
**Pull request by vanshika2906**
Fixed #78.

#### Description
Issue FIXES #78

#### Describe the changes you've made

1.Added a new emergency button at the bottom-left corner by clicking on it user will land to a google map page.
2.Added component Emergency-->emergency.js and emergency.module.css
3.Imported Emergency component to homepage.

#### Checklist

- [ ] I have added my name in the contributors list at the end of README.md file.
- [x ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [ x] The title of my pull request is a short description of the requested changes.
- [x] Open Source Program names(OPTIONAL: If you participated in any open-source program then please mention the program name here)

### CODE REVIEW

**Comment by khushishikhu** [comment]
@vanshika2906 can you please send us the screenshot of the UI change you have done

**Comment by vanshika2906** [comment]
Hi, @khushishikhu. Here is the screenshot for the Emergency button. Let me know if there is any you want me to do. Thankyou!
image

**Comment by khushishikhu** [comment]
@vanshika2906 LGTM!! I just need to do testing. You can move ahead for some other issue as well

**Comment by khushishikhu** [comment]
@vanshika2906 I can you add a kind of options to pop out when someone clicks the button. those options will include where we are looking for like restrooms, hospital or any place for eating

**Comment by vanshika2906** [comment]
Hi @khushishikhu. Added options to the the Restrooms button. Please find attached screenshots for your reference.ThankYou!
Before clicking to the Restroom button.
image
After clicking on the Restroom button.
image

**Comment by khushishikhu** [comment]
@vanshika2906 please solve merge conflicts. update your branch and make the UI similar to "click to chat" button

**Comment by vanshika2906** [comment]
@khushishikhu updated

**Comment by Aaishpra** [comment]
Can we get some screenshots for this UI update.
Thanks

**Comment by vanshika2906** [comment]
Hi @Aaishpra . Same as the above just a minute change in position and resolved conflicts.Thankyou!
image

**Comment by K-Kumar-01** [comment]
@vanshika2906 
I don't like the outline which is there on the restrooms when it is focused.
Also, it would be better if there is a small gap between public, restaurants, hospitals, and restrooms. Currently, it looks congested.

**Comment by vanshika2906** [comment]
> @vanshika2906
> I don't like the outline which is there on the restrooms when it is focused.
> Also, it would be better if there is a small gap between the public, restaurants, hospitals, and restrooms. Currently, it looks congested.

Hi @K-Kumar-01 , please find attached for the changes you asked. Please let me know if you want more changes. Thankyou!
image

**Review by Aaishpra — APPROVED** [review]
Pretty good work here @vanshika2906

**Pull request merged**
