### PR TITLE
Card made legible so that notes can be seen!

### LINKED ISSUE #149: Notes not visible clearly.
**Describe the bug**
The notes we take are not visible properly as the background not transparent.

**Expected behavior**
The notes should be visible clearly and the background should be transparent.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows [e.g. iOS]
 - Browser chrome
 - Version 

**Additional context**

### PR DESCRIPTION
**Pull request by akshay1027**
#### Description
Issue FIXES #149 

#### Describe the changes you've made
The notes were not visible, so i thought we can reduce the opacity of the background image. But since background image is a global file, every other page was also affected if I change there. After Thinking and experimenting, I have come up with a fix for this bug! please check it out @khushishikhu 

#### Checklist

- [ ] I have added my name in the contributors list at the end of README.md file.
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.
- [x] The title of my pull request is a short description of the requested changes.
- [ ] Open Source Program names(OPTIONAL: If you participated in any open-source program then please mention the program name here) GSSOC'21

### CODE REVIEW

**Review by khushishikhu — COMMENTED** [review]
@akshay1027 you don't need to remove the background, just make the notes cards in a way that it will not contradict with the background. you can design that in various ways by googling about it, you will find plenty of designs with their source code.

**Comment by akshay1027** [comment]
@khushishikhu please check out the tips page, i following the same design pattern here in notes page, designing card can be done but i think still we might have the same issue. This is my opinion.

**Comment by akshay1027** [comment]
I have made the changes @khushishikhu, please check it out!

**Review by khushishikhu — COMMENTED** [review]
@akshay1027 decrease the width of the notes cards a bit please. rest looks good now.

**Comment by akshay1027** [comment]
Have used pink as the background colour for the title (of card) and box-shadow as pink is mostly used as a secondary colour in the website!

**Review by Aaishpra — APPROVED** [review]
Lgtm

**Pull request merged**
