### PR TITLE
 Fixed Toggle Option Visibility

### LINKED ISSUE #123: Improve Toggle background
There should be some background so that **toggle** options can be clearly visible. 
I like to work on this issue (GSSOC_21 participant).

Screenshot (77)_LI

### PR DESCRIPTION
**Pull request by bhavesh1334**
Fixes #123

#### Description
Issue FIXES #
ISSUE #123 

#### Describe the changes you've made
I have made changes on navbar.css file and style.js to fix sidebar visibility issue and have done minor adjustment .

#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
NA
#### Additional context (OPTIONAL)

Screenshot (82)

### CODE REVIEW

**Comment by ambivert-sam** [comment]
hey ! @bhavesh1334 do have any idea why its showing "all checks have failed" the same thing happened with my PR also!!

**Comment by bhavesh1334** [comment]
> hey ! @bhavesh1334 do have any idea why its showing "all checks have failed" the same thing happened with my PR also!!
@ambivert-sam  No idea what's the  actual problem with it.

**Comment by bhavesh1334** [comment]
hello! @khushishikhu, @Aaishpra Please review this pr , Why I am getting this issue **all check failed**, how this can be resolve.

**Comment by Aaishpra** [comment]
Don't worry @bhavesh1334 @ambivert-sam it's vercel deployment which is failing nothing to do with the PR.
We will review it once we get some time @bhavesh1334

**Comment by bhavesh1334** [comment]
> Don't worry @bhavesh1334 @ambivert-sam it's vercel deployment which is failing nothing to do with the PR.
> We will review it once we get some time @bhavesh1334

 ok  thanks..

**Comment by Aaishpra** [comment]
Please remove the merge conflicts @bhavesh1334

**Comment by bhavesh1334** [comment]
> Please remove the merge conflicts @bhavesh1334

Not able to resolve , as this "resolve conflicts" button is not clickable from my side .

Screenshot (84)_LI

**Comment by bhavesh1334** [comment]
> > Please remove the merge conflicts @bhavesh1334
> 
> Not able to resolve , as this "resolve conflicts" button is not clickable from my side .
> 
> Screenshot (84)_LI

Any alternative or should I send another pr for this issue .

**Comment by bhavesh1334** [comment]
> > Please remove the merge conflicts @bhavesh1334
> 
> Not able to resolve , as this "resolve conflicts" button is not clickable from my side .
> 
> Screenshot (84)_LI

@Aaishpra please something to resolve this issue.

**Comment by bhavesh1334** [comment]
> > Please remove the merge conflicts @bhavesh1334
> 
> Not able to resolve , as this "resolve conflicts" button is not clickable from my side .
> 
> Screenshot (84)_LI

@Aaishpra  Please suggest something to resolve this problem.

**Comment by Aaishpra** [comment]
@bhavesh1334 i just checked this out, and this is because the merge conflicts on your PR are too big to be resolved on Github GUI(on the website)and can be solved only on your local machine (ie your laptop).
For solving this you can either do the following which is the preferred method
1. Solve merge conflicts without creating additional merge commit (best way) 
`git checkout your-branch
git rebase upstream/master`

2. Create additional merge commit after solving conflicts
`git checkout your-branch
git merge upstream/master`

You can use these above methods to solve the conflicts if you're interested in learning something new🚀

Or if this is too overwhelming for you (which can be the case if you are a beginner on Github) you can serve your work in a new PR. I am totally cool with both options, whichever works for you use it 🙌🏻

References: https://github.community/t/resolve-conflict-button-is-disabled/123773

https://stackoverflow.com/questions/59110548/github-resolve-conflicts-button-disabled#:~:text=2%20Answers&text=If%20the%20Resolve%20conflicts%20button,for%20pull%20requests%20between%20repositories.

**Comment by khushishikhu** [comment]
-

**Pull request closed without merging**
