### PR TITLE
FAQs

### LINKED ISSUE #334: FAqs section in navbar
## Is your feature request related to a problem? Please describe.
There should be a section in navbar FAqs for the period beginner girls and for the others too.

### PR DESCRIPTION
**Pull request by kumarishalini6**
Issue FIXES #334 

I have created a FAQs section in navbar and design the page.

https://user-images.githubusercontent.com/69043944/119535374-61b2f800-bd34-11eb-884f-b70c880f9876.mp4

https://user-images.githubusercontent.com/69043944/119535469-8018f380-bd34-11eb-80ec-59016788e27d.mp4

https://user-images.githubusercontent.com/69043944/119535581-a2ab0c80-bd34-11eb-8ee7-027042d2febe.mp4

### CODE REVIEW

**Comment by kumarishalini6** [comment]
@khushishikhu can you please tell me why the checks are failed?

**Comment by khushishikhu** [comment]
@kumarishalini6 I will check out why your checks are failing. try to run `yarn run build` maybe you will get to know what is it causing the error

**Comment by kumarishalini6** [comment]
Ok

**Comment by kumarishalini6** [comment]
Tried ,but not working

**Comment by kumarishalini6** [comment]
can you please check it once

**Comment by kumarishalini6** [comment]
send it again

**Pull request closed without merging**
