### PR TITLE
Buttons improved.

### PR DESCRIPTION
**Pull request by padmajabhol**
Buttons are improved, hover effect is added, font is changed.

### CODE REVIEW

**Comment by khushishikhu** [comment]
@padmajabhol Can you please add the screenshot over here to see how does it look like. Whenever you are doing any issue related to UI/UX just add the screenshot too, it is a good practice

**Comment by padmajabhol** [comment]
> @padmajabhol Can you please add the screenshot over here to see how does it look like. Whenever you are doing any issue related to UI/UX just add the screenshot too, it is a good practice

Screenshot (9)
Here it is, I ll keep this in my mind from next time.

**Comment by khushishikhu** [comment]
@padmajabhol LGTM!! Thank you for your contribution.

**Review by Aaishpra — APPROVED** [review]
LGTM 🎉 Congratulations on your first commit to the Repo @padmajabhol

**Pull request merged**
