### PR TITLE
made tips section responsive 

### LINKED ISSUE #349: Tips section is not responsive
**Describe the bug**

I would like to make the tips page responsive 
image

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

### PR DESCRIPTION
**Pull request by gnikita432**
#### Description
Issue FIXES #349 

made tips section responsive 
image

#### Checklist

- [ ] I have added my name in the contributors list at the end of README.md file.
- [x] My code follows the code style of this project.
- [] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ x] I have added tests to cover my changes.
- [ x] All new and existing tests passed.
- [ x] The title of my pull request is a short description of the requested changes.
- [ x] Open Source Program names(OPTIONAL: If you participated in any open-source program then please mention the program name here)

### CODE REVIEW

**Comment by khushishikhu** [comment]
@gnikita432 update your branch

**Comment by gnikita432** [comment]
@khushishikhu  I am unable to understand? what to update?

**Comment by khushishikhu** [comment]
@gnikita432 https://stackoverflow.com/questions/3876977/update-git-branches-from-master refer to this article. for updating your forked git branch (gnikita432:tips)

**Comment by gnikita432** [comment]
@khushishikhu I have updated the branch. Can you please check it now?

**Comment by gnikita432** [comment]
@khushishikhu can you please check the PR now

**Comment by gnikita432** [comment]
@khushishikhu  please have a look here so that I can make any changes if needed .

**Comment by gnikita432** [comment]
@Aaishpra ?

**Comment by gnikita432** [comment]
@khushishikhu

**Pull request merged**
