### PR TITLE
added link to homepage to logo on navbar

### LINKED ISSUE #145: Logo on top left corner should redirect to home page.
The logo on the top left corner on the navbar of the website should redirect user to the homepage. Right now it does nothing.

**Screenshots**

image

Please assign this issue to me.

### PR DESCRIPTION
**Pull request by keshavga1209**
#### Description
Issue FIXES #145

#### Describe the changes you've made

added link to homepage to logo on navbar.

#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)

NA

#### Checklist

- [ ] I have added my name in the contributors list at the end of README.md file.
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.
- [x] The title of my pull request is a short description of the requested changes.
- [x] Open Source Program names (GSSOC'21)

### CODE REVIEW

**Comment by khushishikhu** [comment]
@keshavga1209 Remove the hovering effect from the Logo

**Comment by keshavga1209** [comment]
Done. Looking fine now?

**Comment by khushishikhu** [comment]
@keshavga1209 just update your branch. may be it will resolve conflicts too

**Comment by keshavga1209** [comment]
@khushishikhu sorry for bothering but didnt get what should I do to resolve the conflict. Can u elaborate more please?

**Pull request merged**
