### PR TITLE
Added responsivness to the website

### LINKED ISSUE #211: Responsive website
**Describe the bug**

The home page is not responsive for mobile view 

**To Reproduce**

**Expected behavior**

**Screenshots**

image

**Desktop (please complete the following information):**
 - OS: windows
 - Browser chrome

**Smartphone (please complete the following information):**

**Additional context**

I want to work on this issue to make the website mobile friendly

### PR DESCRIPTION
**Pull request by gnikita432**
#### Description
Issue FIXES #211

#### Describe the changes you've made
 Added responsiveness in the whole website
s1
s2

#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)

NA

#### Checklist

- [ ] I have added my name in the contributors list at the end of README.md file.
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.
- [x] The title of my pull request is a short description of the requested changes.
- [x] Open Source Program names(OPTIONAL: If you participated in any open-source program then please mention the program name here)GSSOC

### CODE REVIEW

**Comment by gnikita432** [comment]
@Aaishpra I am getting all checks have failed. Can you please review the PR

**Comment by Aaishpra** [comment]
No problem with the checks failing they are just deployment checks of vercel. About the PR review i will review it once i get some time.

**Comment by gnikita432** [comment]
Ohh okay, Thank you.

**Review by khushishikhu — APPROVED** [review]
LGTM!!

**Pull request merged**
