### PR TITLE
Prescriptions/Advice based on Quiz response

### LINKED ISSUE #22: Coding: Prescriptions
## Description
According to the marks in quiz. Give the user the links to go for the page where all the remedies and Prescription are listed for the time Being as it will be added in the Tips Page

### PR DESCRIPTION
**Pull request by A-HK**
#### Description
Issue FIXES #22

#### Describe the changes you've made

Added a result card at the end of the quiz that toggles recommendations based on the response of the user in the quiz.

#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)

Not responsive for all screen sizes.

#### Additional context (OPTIONAL)

The user gets recommendations based on the selection of each answer in the quiz : 
quiz_ans_pic
quiz_3

If the user has selected all options indicating that she has no current difficulties, a corresponding recommendation card is displayed : 
quiz_ans_pic_2

#### Test plan (OPTIONAL)

- Go to the Quiz page
- Select answers of your choice in the quiz.
- Click on the 'Tell Me More' button to see custom results displayed.

#### Checklist

- [ ] I have added my name in the contributors list at the end of README.md file.
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [x] The title of my pull request is a short description of the requested changes.
- [x] Open Source Program names - GSSoC'21

### CODE REVIEW

**Comment by A-HK** [comment]
Hey @khushishikhu  @Aaishpra , really sorry to bother you, but two of my merged PRs - #133 and #137 - don't seem to have both the gssoc and level labels on them. If you could look into it whenever you have time, that would be great!

**Comment by khushishikhu** [comment]
@A-HK sorry, we didn't noticed that. Thank you for reminding us I have added the labels in both of your PRs. Happy!!

**Comment by khushishikhu** [comment]
@A-HK can you please test your PR because I have tested it and it was throwing some errors

**Comment by A-HK** [comment]
Ah, so sorry for the trouble!
It seems to run fine on my local machine.
If it's not too much work, can you show me a picture of the errors thrown so that I can figure out what to fix?

**Comment by A-HK** [comment]
This is how it works on my end @khushishikhu 

https://user-images.githubusercontent.com/73497800/115700377-3e3b0d00-a384-11eb-9c88-339366e31671.mp4

**Comment by A-HK** [comment]
Hey @khushishikhu , please inform me about the above if you can!

**Comment by khushishikhu** [comment]
@A-HK I will test your PR at the EOD until then You are allowed to work on any other issue if you want. I was a bit busy with some of my own work.

**Comment by A-HK** [comment]
Of course! Please take your time. Again, sorry for this trouble.

**Review by khushishikhu — APPROVED** [review]
@A-HK  LGTM!! 💯 🎉  Thank you so much for contributing

**Pull request merged**
