### PR TITLE
Contact us form email.js

### LINKED ISSUE #185: Backend for contact us form
**Describe the bug**
create the backend ( database, API endpoints etc) needed for contact us form!

**To Reproduce**
1. See error in the footer of homepage

### PR DESCRIPTION
**Pull request by akshay1027**
#### Description
Issue FIXES #185 

#### Describe the changes you've made

changed div tag to Form tag, used the form "on submitting" method to handle forms and state! added subject input box as well!

Screenshots:  

  
  

#### Checklist

- [ ] I have added my name in the contributors list at the end of README.md file.
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [ ] The title of my pull request is a short description of the requested changes.
- [ ] Open Source Program names(OPTIONAL: If you participated in any open-source program then please mention the program name here)

### CODE REVIEW

**Comment by akshay1027** [comment]
@Aaishpra @khushishikhu The emailjs setup is same as in this article( https://medium.com/weekly-webtips/simple-react-contact-form-without-back-end-9fa06eff52d9 ) but I have used a different method to handle forms! Also, don't forget to set up the .enn files as well! Let me know about the changes!

**Comment by khushishikhu** [comment]
@akshay1027 can you please write the instructions in the Readme.md of how to set up the .env file

**Comment by akshay1027** [comment]
I myself, don't know how to use .env files in next js and also in frontend. Or else I would have done that as well. I would be happy to learn from you! While I tested, I directly used the API keys... @khushishikhu

**Comment by Aaishpra** [comment]
@K-Kumar-01 can you help with this.

**Comment by akshay1027** [comment]
@Aaishpra we first have to setup the mail, so we have to do it in email.js website, if you can give me your mail and password, I can do this for you. I have asked @khushishikhu but have not got any reply yet

**Comment by Aaishpra** [comment]
I get it, and i think this can be done after someone reviews the code for us @akshay1027 first we need to finalize (might use a dummy id for this) and when every thing works fine we can go forward using the organisation's email, which can be done by me or @khushishikhu

**Comment by akshay1027** [comment]
Cool!

**Comment by K-Kumar-01** [comment]
@akshay1027 
Is it possible for you to record a small video demonstrating the working of the code?

**Comment by akshay1027** [comment]
Okay I will try 🙌🏻, you guys tested it ? Facing any problems ?

**Comment by akshay1027** [comment]
https://www.youtube.com/watch?v=NgWGllOjkbs check out this video , i learnt from here @K-Kumar-01

**Comment by K-Kumar-01** [comment]
> https://www.youtube.com/watch?v=NgWGllOjkbs check out this video , i learnt from here @K-Kumar-01

@akshay1027 
This seems fine to me, but before merging we need to set up the .env file as well as update the PR to avoid conflicts.
As for the env file [here ](https://nextjs.org/docs/basic-features/environment-variables) is a link that I think might be helpful.

@Aaishpra the code seems fine to me. I think the key needs to be generated for which you can have a discussion with @akshay1027

**Comment by akshay1027** [comment]
@khushishikhu even if I set up the .env file, will I be able to push it? I think we cant push files which proceeds with dot "
."

**Comment by akshay1027** [comment]
i have made the changes and tested it @khushishikhu @K-Kumar-01! now you just have to add API keys in the .env file :)

**Comment by K-Kumar-01** [comment]
> @khushishikhu even if I set up the .env file, will I be able to push it? I think we cant push files which proceeds with dot "
> ."

@akshay1027 
One can push .env files but it is not advisable to push such files as they contain sensitive information. I think @Aaishpra or @khushishikhu will do that part. However, can you please resolve the conflicts?

**Comment by akshay1027** [comment]
conflicts resolved

**Comment by Aaishpra** [comment]
Thanks for this @akshay1027 i will be free in a day or two and then we can have discussion on discord about this. Thanks for your patience

**Comment by khushishikhu** [comment]
@akshay1027 can you please resolve the conflicts. Then I will add the credentials of .env file after merging this PR

**Comment by akshay1027** [comment]
Hey @khushishikhu, am not able to resolve the yarn.lock and package-lock files, My laptop is getting hanged whenever I open them! Can you please resolve them

**Comment by khushishikhu** [comment]
@akshay1027 I see there are so many conflicts and difficult to resolve. If you are comfortable can you please open another PR like this one only to not face this thing.

**Comment by akshay1027** [comment]
That good idea!! Also shall I just send the code? Like can you manually install the packages, because the problem is occurring as different people are using yarn or npm to install packages.

**Pull request closed without merging**
