### PR TITLE
Fixed Contact Form Responsiveness

### PR DESCRIPTION
**Pull request by Saatvik21**
#### Description
Issue FIXES #

Fixes: #366 

#### Describe the changes you've made
I've made the text area of the comment section and the submit button responsive and aligned.

#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
`NA`

#### Checklist

- [ ] I have added my name in the contributors list at the end of README.md file.
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.
- [x] The title of my pull request is a short description of the requested changes.
- [x] Open Source Program names(OPTIONAL: If you participated in any open-source program then please mention the program name here) ***`gssoc'21`***

### CODE REVIEW

**Comment by Saatvik21** [comment]
@khushishikhu idk why the deployment is failing on this one? 🤔

**Comment by khushishikhu** [comment]
@Saatvik21 Try updating your branch after that I will look into your error

**Comment by Saatvik21** [comment]
> @Saatvik21 Try updating your branch after that I will look into your error

Done. Please review now!

**Review by khushishikhu — APPROVED** [review]
@Saatvik21 LGTM!!

**Pull request merged**
