### PR TITLE
implement dark mode

### LINKED ISSUE #69: Feat: Implement Dark Mode
## Description
Implement the Dark Mode feature in the website

## Additional context
Must add the screenshot of how it will look like.

### PR DESCRIPTION
**Pull request by subhangi2731**
#### Description
Implement the Dark Mode feature in the website

Issue FIXES #69 

#### Describe the changes you've made
I have made changes in Contactus.js and footer.module.css in components/footer and made modifications in it and then created a homepage.js file in public and modified file package.json in periodo/periodo

#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
NA

#### Checklist

- [x] I have added my name in the contributors list at the end of README.md file.
- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.
- [x] The title of my pull request is a short description of the requested changes.
- [x] Open Source Program names(KWOC , NWOC)
Screenshot from 2021-05-18 22-26-18

### CODE REVIEW

**Comment by subhangi2731** [comment]
@khushishikhu @Aaishpra please review and merge my pr

**Review by khushishikhu — APPROVED** [review]
@subhangi2731  LGTM!!

**Comment by khushishikhu** [comment]
@subhangi2731 can you make another PR as well bcoz I have merged but it is actually not showing the dark more icon

**Comment by subhangi2731** [comment]
@khushishikhu run npm i so that darkmode-js will be installed then in bottom left one icon will be shown by running the project.. dark mode is showing in my one

**Comment by khushishikhu** [comment]
@subhangi2731 I did that but it is still not showing me, it is not even showing in the deployment. Can you please check it out once again and your code to this PR

**Comment by subhangi2731** [comment]
@khushishikhu yes okay I will do that and create a pr

**Pull request merged**
