### PR TITLE
Added CONTRIBUTING.md

### LINKED ISSUE #10: docs: Make CONTRIBUTING.md
## Description
Add the contributing guidelines in a folder(CONTRIBUTING.md)

## Status
Approval of two mentors.

### PR DESCRIPTION
**Pull request by vismitap**
Fixed #10

#### Description
Issue FIXES #10 

#### Describe the changes you've made
* Added `CONTRIBUTING.md` file in root `.github`.
* Deleted the second `.github` which was inside period react app.
image
image
image
image

#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
NA 

#### Checklist

- [ ] I have added my name in the contributors list at the end of README.md file.
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.
- [x] The title of my pull request is a short description of the requested changes.
- [x] Open Source Program names(OPTIONAL: If you participated in any open-source program then please mention the program name here)

Participating in GSSOC'21.

### CODE REVIEW

**Review by khushishikhu — CHANGES_REQUESTED** [review]
Can you also link this file in the readme

**Comment by vismitap** [comment]
> Can you also link this file in the readme

Yes sure!

**Comment by vismitap** [comment]
Done!

**Review by Aaishpra — APPROVED** [review]
LGTM 🚀  Thanks for your contribution @vismitap and very detailed documentation for the project

**Pull request merged**
