### PR TITLE
Change rating icons #20

### LINKED ISSUE #20: feat: Change rating icons
## Description
Change the icons of the ratings
image

### PR DESCRIPTION
**Pull request by shairanshrawat**
#### Description
Issue FIXES #20 

#### Describe the changes you've made
 Designed the UI design for rating icons

#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
NA

#### Test plan (OPTIONAL)
 https://www.figma.com/file/gCgZ9vu1gnPoajCps9w9Gz/Periodo?node-id=31%3A2 
This is the Figma link for the design

#### Checklist

- [ ] I have added my name in the contributors list at the end of README.md file.
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [x] The title of my pull request is a short description of the requested changes.
- [ ] Open Source Program names(OPTIONAL: If you participated in any open-source program then please mention the program name here)

### CODE REVIEW

**Comment by khushishikhu** [comment]
@shairanshrawat This is not the thing I asked for in Issue. You have to implement that whole feature in the flow page were the ratings are there. You should not just add your figma files in the repository which does nothing. I hope you got what I am trying to say. Please refine that and then show, we will appreciate your efforts

**Comment by Aaishpra** [comment]
@khushishikhu we can merge this I think and open a new issue for a contributor to work on it.
She worked so hard on it 💯  , I don't want her efforts to go in vain.

**Review by Aaishpra — APPROVED** [review]

**Comment by Aaishpra** [comment]
@shairanshrawat do you want to implement the design as @khushishikhu asked you or we can let any other contributor work on it.

**Comment by khushishikhu** [comment]
@Aaishpra yaa sure, I like your idea 👍

**Comment by shairanshrawat** [comment]
> @shairanshrawat do you want to implement the design as @khushishikhu asked you or we can let any other contributor work on it.

yes I will work on implementing it as well , since I already mention @khushishikhu I had my exam so i wasn't able to will do it asap

**Pull request merged**
