### PR TITLE
Automated Slider added in Home

### PR DESCRIPTION
**Pull request by WebVishal**
hi@khushishikhu I have added the Automated slider  please check the code and merge it in the main branch
I have added a short clip

Issue no #118 

https://user-images.githubusercontent.com/76445546/112091593-b6fb4d80-8bbb-11eb-8370-5e56e168bab1.mp4

### CODE REVIEW

**Comment by khushishikhu** [comment]
@WebVishal please solve the merge conflicts

**Comment by WebVishal** [comment]
hi @khushishikhu, I have fixed the conflict issue, review the code

**Comment by khushishikhu** [comment]
@WebVishal I have checked your PR the images are good but the orientation of the image doesn't seem proper as the should be only one image to display in one slide and bit the some portion of the next image slide. And also can you just decrease the height of the images because it is taking the whole screen currently. Please make these suggested changes so that I will happily merge this. Hope you got my point, if you need any help do ping us , we will sort out✌️

**Comment by WebVishal** [comment]
@khushishikhu When I Decrease the height of the image, then the background behind it is not seen properly, can I remove it? and "started component" add on slider images

**Comment by khushishikhu** [comment]
@WebVishal Background of the webpage, you mean to say?

**Comment by WebVishal** [comment]
hi @khushishikhu,  After the height of the image is reduced and some modifications look like this 




https://user-images.githubusercontent.com/76445546/112756945-12d33580-9005-11eb-8813-92ccb35b8d97.mp4

**Comment by WebVishal** [comment]
hi @khushishikhu, can review the code

**Comment by khushishikhu** [comment]
@WebVishal Hey can you please update this branch. And can you just set the images in a way that the content should not overlap with the images it has on the webpage.

**Comment by WebVishal** [comment]
hi @khushishikhu Can I work on this is the issue or it is closed   
Sorry I was busy with my freelancer project for the last 2 to 3 weeks now I want to contribute to this project can I work on this issue again

**Comment by khushishikhu** [comment]
@WebVishal Sorry as you were inactive for so many days. I have assigned this issue to someone else. you can take any other issue where no one is working. 
Thank you

**Pull request closed without merging**
