### PR TITLE
calander with timer

### LINKED ISSUE #353: Timer
I want to make a timer to check blood flow. There is a clock and buttons start, stop, reset . 
I want to add these features in calander page when someone open that page there will be 2 option of timer and calander . 
I want to work on this issue under GSSoC'21 participant.

### PR DESCRIPTION
**Pull request by kumarishalini6**
fixes #353 
I have created a page where we have 2 buttons timer, calendar on clicking that render us to the respective page.

https://user-images.githubusercontent.com/69043944/119989786-0c652980-bf74-11eb-9c0a-43dbf2f5f8d5.mp4

https://user-images.githubusercontent.com/69043944/119989869-269f0780-bf74-11eb-963f-7dee4212ed32.mp4

### CODE REVIEW

**Comment by kumarishalini6** [comment]
@khushishikhu  Please merge my PR . The GSSoC'21 is about to end

**Comment by kumarishalini6** [comment]
@Ishikakhurana please review this too

**Comment by khushishikhu** [comment]
@kumarishalini6 I would suggest. Make the timer with a calendar page only. Instead of separating them and having bars to open

**Comment by kumarishalini6** [comment]
Ok

**Comment by kumarishalini6** [comment]
@khushishikhu can you please  check why the deployment are failing

**Comment by kumarishalini6** [comment]
@khushishikhu  now you can merge this issue I have made changes

**Pull request merged**
