### PR TITLE
Added loginPage

### PR DESCRIPTION
**Pull request by prerna2712**
#### Description
Issue FIXES #

#### Checklist

- [ ] I have added my name in the contributors list at the end of README.md file.
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [ ] The title of my pull request is a short description of the requested changes.
- [ ] Open Source Program names(OPTIONAL: If you participated in any open-source program then please mention the program name here)

### CODE REVIEW

**Comment by khushishikhu** [comment]
@prerna2712 can you please add the screenshot of how you have designed and put the issue number as given in PR template

**Comment by prerna2712** [comment]
Sure

**Comment by prerna2712** [comment]
Screenshot from 2021-03-19 16-54-04
I plan to add 2 buttons instead of this. 
1. Login button
2. Signup button
which in turn will open seperate modals. This is something similar to spotify desktop.

**Comment by khushishikhu** [comment]
kjfkvh

**Comment by prerna2712** [comment]
Should I resolve the conflicts? There is an issue with the page structure in index.js

**Comment by Aaishpra** [comment]
Yess!

**Comment by prerna2712** [comment]
Sure

**Comment by prerna2712** [comment]
It still shows somw conflicts. Can anyone help resolve them?
Thank You.

**Comment by khushishikhu** [comment]
@prerna2712 Please update your branch in which you have made the PR. We will solve the merge conflict then . No need to worry

**Comment by prerna2712** [comment]
It shows the branch is already up to date. Should I make a pull request then?

**Comment by khushishikhu** [comment]
@prerna2712 your branch is not updated yet, I have checked that your branch is 35 commits behind. Please update so that I can merge this PR

**Comment by prerna2712** [comment]
Okay, looking into it.

**Review by Aaishpra — APPROVED** [review]
Thanks for your contribution 🎉

**Comment by prerna2712** [comment]
Thank you :)

**Pull request merged**
