### PR TITLE
Flowpage UI improved

### LINKED ISSUE #199: Improve UI in "/flow" page
## Is your feature request related to a problem? Please describe.
The cards can be improved in the "/flow" page!

Additional Context:
this is the page am referring to:

### PR DESCRIPTION
**Pull request by akshay1027**
#### Description
Issue FIXES #199 

Improved UI and layout of page | responsive as well 

Screenshots:  

screen size is reduced to 80% so that you can see full layout  

  

#### Checklist

- [ ] I have added my name in the contributors list at the end of README.md file.
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [ ] The title of my pull request is a short description of the requested changes.
- [ ] Open Source Program names(OPTIONAL: If you participated in any open-source program then please mention the program name here)

### CODE REVIEW

**Comment by akshay1027** [comment]
@K-Kumar-01 @khushishikhu @Aaishpra let me know if you need anhy changes!

**Comment by K-Kumar-01** [comment]
@akshay1027 
Rather than changing the complete layout I think it would be better to add appropriate media queries for this

**Comment by akshay1027** [comment]
I have added media queries to make it fully responsive, but if you don't like it, I will change it to 2 coloum in a row , no problem, changing right away

**Comment by K-Kumar-01** [comment]
> I have added media queries to make it fully responsive, but if you don't like it, I will change it to 2 coloum in a row , no problem, changing right away

I think it would be better to have a 4 3 2 1 layout depending on various screen sizes. Also aligning the content to center both  horizontally as well as vertically

**Comment by akshay1027** [comment]
How 4 3 2 1 ? We have 8 cards as of now .. you mean cards right or am I misunderstanding something

**Comment by akshay1027** [comment]
This is how it looks now @K-Kumar-01, I can try 3 in a row but then it would too small I think

**Comment by akshay1027** [comment]
How about this?

**Comment by akshay1027** [comment]
"breast tenderness" card is bigger than other cards, if we place it a row with other cards, it won't look good is what I feel! That is my opinion! You can say how you want it to be! if you can tell as soon as possible, we can finish this now itself, I can also work on next issues

**Comment by K-Kumar-01** [comment]
@akshay1027 Try to keep it 3 3 2
Rechange the ordering of breast tenderness, make it last. It does not look good this way.

**Comment by akshay1027** [comment]
okay. done as you suggested. check it out:

**Comment by K-Kumar-01** [comment]
> okay. done as you suggested. check it out:
> 
> 

can you push it so I can see the deployed preview?

**Comment by akshay1027** [comment]
cool

**Comment by K-Kumar-01** [comment]
@akshay1027 
Please follow the commit guidelines also whenever you commit the changes

**Comment by akshay1027** [comment]
There is a edge case in this for tab/medium sized window as am checking now, any ways on how to change it 2 coloums in a row instead of 3 for medium screen ?  I will make an issue for this and make a PR after I complete it, if you have any suggestions let me know

**Comment by akshay1027** [comment]
Also please add labels :)

**Comment by K-Kumar-01** [comment]
> There is a edge case in this for tab/medium sized window as am checking now, any ways on how to change it 2 coloums in a row instead of 3 for medium screen ? I will make an issue for this and make a PR after I complete it, if you have any suggestions let me know

Can you share the image for this one?

**Comment by akshay1027** [comment]
as we changed to 3 in a row its causing problems here

**Comment by K-Kumar-01** [comment]
> as we changed to 3 in a row its causing problems here
> 
> 

This is a whole different issue.
It was causing problems beforehand also and there is already an issue opened regrading this - #243 
Here instead of going to quiz visit any page and you will be able to see this

**Comment by akshay1027** [comment]
will this work for medium screen? 
I have added media queries

**Comment by K-Kumar-01** [comment]
> will this work for medium screen?
> I have added media queries
> 
> 

Will the 2 block work here?

**Comment by akshay1027** [comment]
> > as we changed to 3 in a row its causing problems here
> > 
> 
> This is a whole different issue.
> It was causing problems beforehand also and there is already an issue opened regrading this - #243
> Here instead of going to quiz visit any page and you will be able to see this
> Although I am not sure whether the 3 blocks issue will still remain even after fixing the above-mentioned issue.

ohh if nobody is doing that, I would be happy to work on it!!

**Comment by akshay1027** [comment]
> > will this work for medium screen?
> > I have added media queries
> > 
> 
> Will the 2 block work here?

No for making this itself I had to add more media queries for all containers, if we want 2 blocks, then we have to do changes in  JSX and render conditionally according to screen size! That would me like how I did for the first layout which I sent but it will take a lot of effort!

**Comment by akshay1027** [comment]
this is how it looks now! i also increased padding and margin along with media queries to make it better

**Comment by K-Kumar-01** [comment]
> > > will this work for medium screen?
> > > I have added media queries
> > > 
> > 
> > 
> > Will the 2 block work here?
> 
> No for making this itself I had to add more media queries for all containers, if we want 2 blocks, then we have to do changes in JSX and render conditionally according to screen size! That would be like how I did for the first layout which I sent but it will take a lot of time and effort

Well, I think that would be better even if it takes time and effort. Feel free to take time and cover up all the corner cases.
In medium-size it should vary between 3 to 2 as it looks suitable to you. In small screen sizes, it should go 1. Feel free to alternate and make any desired styling changes required.

**Comment by K-Kumar-01** [comment]
> this is how it looks now! i also increased padding and margin along with media queries to make it better
> 

adding padding and media queries is temporary workout and not a permanent solution to the problem I suppose

**Comment by K-Kumar-01** [comment]
@akshay1027 
I have reopened the issue. Feel free to make the PR.

**Comment by akshay1027** [comment]
Okay I will try and do it as quickly as possible! 🙌🏻

**Pull request merged**
