### PR TITLE
feat: Fixing Navbar components and adding necessary icons

### LINKED ISSUE #200: Home Page Navbar Alignment
## Is your feature request related to a problem? Please describe.
The content in the  Header section-Navbar is centralized. which is not visually pleasing. Hence the alignment of the elements can be adjusted

## Describe the solution you'd like
The Home button can be placed on the leftmost side, while the rest can be placed on the rightmost side following this order-About Us, Notes, Tips, GynacHelp, Quiz, Calendar, Login.
In addition to this, adding Icons might improve the User Experience. Hence I would like to add related Icons as well.

Image:
image

### PR DESCRIPTION
**Pull request by anhushree**
#### Description
Issue FIXES #200 

#### Describe the changes you've made

Centered the alignment of navbar components.
Shifted Home and AboutUs to the left and others to the right.
Arranged the order of display in the navbar.
Adding icons to certain components in navbar- Home, AboutUs, Login, Logout. 

#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)

NA

#### Checklist

- [x] I have added my name to the contributor's list at the end of the README.md file.
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.
- [x] The title of my pull request is a short description of the requested changes.
- [x] Open Source Program names(OPTIONAL: If you participated in any open-source program then please mention the program name here)GSSoC'21
Screenshots:
image

### CODE REVIEW

**Comment by anhushree** [comment]
@khushishikhu kindly review it.

**Comment by khushishikhu** [comment]
@anhushree always try to add the screenshot of the UI changes you have done. It is a good practice

**Comment by anhushree** [comment]
Sorry @khushishikhu for not attaching screenshots, could you kindly review them now? I have updated my comment.
image
As the Navbar has too many elements adding icons only to those main components will balance the visual experience of the user. Hence I added Icons for just three of the components, Kindly look at the below screenshot
image
It kinda looks cramped, well do let me know which looks better. I have created a PR where only HOME, ABOUT US, LOGIN has icons .

**Comment by khushishikhu** [comment]
@anhushree   I would suggest to put the icons on all the tabs of navbar it looks so cute!!

**Comment by anhushree** [comment]
> @anhushree I would suggest to put the icons on all the tabs of navbar it looks so cute!!

ok sure ill work on it and update the PR. Thank you so much

**Comment by anhushree** [comment]
@khushishikhu I have updated the PR, Kindly review it 
After adding all icons

image

image

**Review by khushishikhu — APPROVED** [review]
@anhushree LGTM!! 💯  Thank you for the contribution

**Comment by anhushree** [comment]
@khushishikhu can u please assign the labels and level? I'm a GSSoC'21 participant. Apparently, those with labels and levels are only counted. Mine has not been done during the PR merge, kindly check and help me out.

**Comment by khushishikhu** [comment]
@anhushree thank you for reminding me I have added the labels

**Pull request merged**
