### PR TITLE
Added ChatBot Feature

### LINKED ISSUE #300: Adding Speech Recognition and Synthesis feature to Chatbot
## Is your feature request related to a problem? Please describe.

Speech Recognition and Speech Synthesis feature to Chatbot

## Describe the solution you'd like

Adding a speech recognition feature where user can use his/her voice to type and speech synthesis where chatbot reads out the message for the user.

### PR DESCRIPTION
**Pull request by vanshika2906**
#### Description
Issue FIXES #300

#### Describe the changes you've made

Added speech and speech recognition feature in the chatbot.

#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)

NA

#### Checklist

- [ ] I have added my name in the contributors list at the end of README.md file.
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [x] The title of my pull request is a short description of the requested changes.
- [ ] Open Source Program names(OPTIONAL: If you participated in any open-source program then please mention the program name here)

### CODE REVIEW

**Comment by khushishikhu** [comment]
@vanshika2906 please check why is deployment is failing

**Comment by vanshika2906** [comment]
> @vanshika2906 please check why is deployment is failing

Hi @khushishikhu, I am not familiar with vercel, Can you guide me how to remove errors for deployment. Recently I tried an another commit but failed again. I will really help appreciate your help. Thankyou!

**Comment by khushishikhu** [comment]
@vanshika2906 I see your branch is not updated. Please update your branch maybe this failing will resolve.

**Comment by vanshika2906** [comment]
Hi @khushishikhu , I am now in a bit of struggle. Tried to update my branch using rebasing but got 157 files changed at the end, may be because of mistakes done by me. Can you help me out in this or should I again fork repo and then should make a pull request. Please guide me accordingly. Thankyou!

**Comment by khushishikhu** [comment]
@vanshika2906  ya looks like something fuss has created. It's okay no need to worry it happens while we are learning git. It is best you can do now to fork again and make another pr closing this.

**Pull request closed without merging**
