### PR TITLE
Fixes:UI improvement Talk to us form

### LINKED ISSUE #262: Talk with us form UI enhancement.
## Is your feature request related to a problem? Please describe.
No.

## Describe the solution you'd like
I would like to make the UI of the talk with us section and will make it more user friendly.

## Additional context
I am  a GSSOC participant.
PLease assign me this issue.

### PR DESCRIPTION
**Pull request by Shivangi-ch**
#### Description
Issue FIXES #262 

#### Describe the changes you've made
I have made the contact us form look attractive.

#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
NA

#### Additional context (OPTIONAL)

Screenshot from 2021-05-16 00-33-52

#### Checklist

- [x] I have added my name in the contributors list at the end of README.md file.
- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.
- [x] The title of my pull request is a short description of the requested changes.
- [x] Open Source Program names(OPTIONAL: If you participated in any open-source program then please mention the program name here)

### CODE REVIEW

**Comment by Shivangi-ch** [comment]
@khushishikhu @Aaishpra Please review!

**Comment by khushishikhu** [comment]
@Shivangi-ch can you please make the background black of this form (just this area) and also update your branch

**Comment by Shivangi-ch** [comment]
@khushishikhu Please review . I have made the requested changes.
Screenshot from 2021-05-17 18-46-20

**Comment by khushishikhu** [comment]
@Shivangi-ch The PR is okay. Once the conflicts will be resolved and merge of this issue #228 . I will merge this too. Till then you can work on some other issues.

**Comment by Shivangi-ch** [comment]
Okay!Thanks.

**Comment by Aaishpra** [comment]
The comments box is breaking the whole UI in mobile view, please correct that

**Comment by Shivangi-ch** [comment]
@Aaishpra @khushishikhu  I have corrected the issue .Please review

**Pull request merged**
