### PR TITLE
Adding more ratings.

### PR DESCRIPTION
**Pull request by codebuzzer01**
More ratings are being added in flow.js.

### CODE REVIEW

**Comment by codebuzzer01** [comment]
Hey! @khushishikhu  I have made the changes. Kindly check and merge the PR.

**Comment by khushishikhu** [comment]
@codebuzzer01 Can you please add the screenshot over here to see how does it look like. Whenever you are doing any issue related to UI/UX just add the screenshot too, it is a good practice

**Review by Aaishpra — COMMENTED** [review]
add the issue number to the PR
like this ⬇️ 
 Fixes: #(issue_number)

**Comment by codebuzzer01** [comment]
ok.

**Pull request closed without merging**
