### PR TITLE
about page addition

### PR DESCRIPTION
**Pull request by A-HK**
#### Description
Issue FIXES #5

#### Describe the changes you've made

- Added about.js, aboutstyle.js and aboutstyle.module.css for development of about page ( also added 4 images under 'public ' directory for display on about page 

)
- Added 'About Us' link in navbar
- Added about.js file under 'pages' directory

#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)

- Images not responsive
- Cards are all of the same colour, unlike those previously approved in the design

#### Additional context (OPTIONAL)

Screenshot (391)
Screenshot (392)

#### Checklist

- [ ] I have added my name in the contributors list at the end of README.md file.
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [x] The title of my pull request is a short description of the requested changes.
- [x] Open Source Program names(OPTIONAL: If you participated in any open-source program then please mention the program name here)
   GirlScript Summer of Code

### CODE REVIEW

**Comment by khushishikhu** [comment]
@A-HK are you able to change the colour of the Cards according to what it was presented in your figma file

**Comment by A-HK** [comment]
No, unfortunately not!
I was hoping either of you could go through my code in the PR, and see where I went wrong, if that's okay?

**Comment by khushishikhu** [comment]
@A-HK I will look into that and tell you accordingly

**Comment by khushishikhu** [comment]
@A-HK Please solve the merge conflict

**Comment by A-HK** [comment]
So sorry for the inconvenience, is it fine now, @khushishikhu ?
If there are more problems, please let me know!
Again, very sorry for the trouble!

**Comment by khushishikhu** [comment]
@A-HK no need to worry😅 Whenever we merge any other PR of the same file. It is normal to have these merge conflict ✌️

**Review by khushishikhu — APPROVED** [review]

**Comment by khushishikhu** [comment]
@A-HK LGTM!! 🎉 we liked your designing thank you so much for making it into action with us. keep contributing.

**Pull request merged**
