### PR TITLE
Add ChatBot feature

### PR DESCRIPTION
**Pull request by parulsurana**
#### Description
Issue FIXES [#9 ](https://github.com/Feminine-Divine/periodo/issues/9)

#### Describe the changes you've made
Added the ChatBot feature to the website.

#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
NA

#### Additional context (OPTIONAL)
Added the Snapshots for the ChatBot.
Chat3
Chat1
Chat2

#### Checklist

- [ ] I have added my name in the contributors list at the end of README.md file.
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [ ] The title of my pull request is a short description of the requested changes.
- [ ] Open Source Program names(OPTIONAL: If you participated in any open-source program then please mention the program name here)

### CODE REVIEW

**Comment by khushishikhu** [comment]
@parulsurana Great work!! I loved it ❤️ 🎉 😍  Thank you so much for your contribution. Keep contributing

**Comment by Aaishpra** [comment]
Can you place the button at the bottom right, it will look better in my opinion then we can open another issue for styling that button.

**Comment by parulsurana** [comment]
Okay I will do that.

**Comment by parulsurana** [comment]
Thank You! @khushishikhu :)

**Comment by parulsurana** [comment]
Hey, @Aaishpra I did the changes you mentioned. Please review the PR now.

**Review by Aaishpra — APPROVED** [review]
Lgtm🚀 thanks for your contribution

**Pull request merged**
