### PR TITLE
Contact us form

### LINKED ISSUE #167: contact us in footer
**Describe the bug**
improve footer UI

### PR DESCRIPTION
**Pull request by akshay1027**
#### Description
Issue FIXES #167 

#### Describe the changes you've made
1) added a contactUs component
2) name, email, message, submit button
3) responsive UI
4) UI design matching existing Footer UI

#### Checklist

- [ ] I have added my name in the contributors list at the end of README.md file.
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [ ] The title of my pull request is a short description of the requested changes.
- [ ] Open Source Program names(OPTIONAL: If you participated in any open-source program then please mention the program name here)

### CODE REVIEW

**Comment by khushishikhu** [comment]
@akshay1027 Please upload the screenshot too everytime you made the UI changes in the website. It is a good practice to be followed and good to understand for admins too.

**Comment by akshay1027** [comment]
should i change the beta as well? or "Contact Us (beta)" is fine? @khushishikhu

**Comment by akshay1027** [comment]
Changes made @khushishikhu!

**Comment by khushishikhu** [comment]
@akshay1027 can you please add the screenshot of the changes you have done

**Comment by akshay1027** [comment]
requested changes made @khushishikhu

**Review by khushishikhu — APPROVED** [review]
@akshay1027 LGTM!! 💯 🎉 Thank you for your contribution

**Pull request merged**
