### PR TITLE
Added Speech Feature To ChatBot.

### LINKED ISSUE #300: Adding Speech Recognition and Synthesis feature to Chatbot
## Is your feature request related to a problem? Please describe.

Speech Recognition and Speech Synthesis feature to Chatbot

## Describe the solution you'd like

Adding a speech recognition feature where user can use his/her voice to type and speech synthesis where chatbot reads out the message for the user.

### PR DESCRIPTION
**Pull request by vanshika2906**
#### Description
Issue FIXES #300

#### Describe the changes you've made

Added speech recognition and speech synthesis feature in chatbot.

#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)

NA

#### Checklist

- [ ] I have added my name in the contributors list at the end of README.md file.
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.
- [x] The title of my pull request is a short description of the requested changes.
- [x] GSSoc'21 Open Source Program names(OPTIONAL: If you participated in any open-source program then please mention the program name here)

### CODE REVIEW

**Comment by vanshika2906** [comment]
Hi @khushishikhu is there anything I need to do from my side?

**Comment by khushishikhu** [comment]
@vanshika2906 there might be something wrong in your code which is why the deployment is failing. Also can add a demo video of how is this working so that would be easy for me to check what you have done.

**Comment by vanshika2906** [comment]
> @vanshika2906 there might be something wrong in your code which is why the deployment is failing. Also can add a demo video of how is this working so that would be easy for me to check what you have done.

Hello @khushishikhu Please go through below link for the reference video. Let me know if any issues. Thankyou!
[Link](https://drive.google.com/file/d/1a_N6C1oaDFn8fO8SfOJmIXrkqmxC8Uao/view?usp=sharing)

**Review by khushishikhu — APPROVED** [review]
@vanshika2906 well it is impressive. so I am merging this pr

**Pull request merged**
