### PR TITLE
home page

### LINKED ISSUE #387: Home page improvement
The home page is looking so odd because of background image in every page the home page should be different and attractive from the others.
I want to work on this issue under GSSoC'21 participant.
@khushishikhu  can I work on this issue.

### PR DESCRIPTION
**Pull request by kumarishalini6**
fixes #387 
I have improved home page
Periodo App - Personal - Microsoft​ Edge 5_30_2021 09_38_32 PM

### CODE REVIEW

**Comment by kumarishalini6** [comment]
@khushishikhu  have a look on this PR i hope you like the change.

**Comment by khushishikhu** [comment]
@kumarishalini6 I want you to make the background image visible again which is already there in the `styles/home.module.css` please open that file and you will find that there is already the images. you just have to make them visible again on the website

**Comment by kumarishalini6** [comment]
Ok let me check

**Comment by kumarishalini6** [comment]
Yaa , I got the image

**Comment by kumarishalini6** [comment]
Wait , @khushishikhu  there is no image exist in home.module.css . Yes there is image in started.module.css which is not visible

**Comment by khushishikhu** [comment]
@kumarishalini6 in `styles/globals.css` I have edited my comment

**Comment by kumarishalini6** [comment]
I got it , let me check why it is not visible

**Comment by kumarishalini6** [comment]
@khushishikhu  please check now the images are visible .
I wanted to ask there is one more image which is also not visible in started.module.css can i make it visible too.??

**Comment by kumarishalini6** [comment]
@khushishikhu  can you please tell me from where you got these images.

**Comment by khushishikhu** [comment]
@kumarishalini6 These images are added by one of our contributor so I don't know where these images are from. No don't make started.module.css image visible

**Comment by kumarishalini6** [comment]
Ok

**Review by khushishikhu — APPROVED** [review]

**Comment by kumarishalini6** [comment]
I guess you forget to add labels please add it

**Pull request merged**
