### PR TITLE
Styled the rating labels

### LINKED ISSUE #44: Styling the Rating Labels
The rating labels can be styled more and the alignment can also be corrected. If accepted, I would like to work on this issue.

### PR DESCRIPTION
**Pull request by sayna3311**
#### Description
Issue FIXES #44 

#### Describe the changes you've made

I have installed a module name 'beauty-stars'

#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)

NA

#### Additional context (OPTIONAL)

image

#### Checklist

- [x] I have added my name in the contributors list at the end of README.md file.
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.
- [x] The title of my pull request is a short description of the requested changes.
- [x] Open Source Program names(OPTIONAL: If you participated in any open-source program then please mention the program name here)

### CODE REVIEW

**Comment by khushishikhu** [comment]
@sayna3311 some more Ratings are also added on the website please checkout them by updating your branch and design them also like these. The designing is great. Thank You 😄

**Comment by sayna3311** [comment]
Oh, sure :)

**Comment by sayna3311** [comment]
image

Did the required changes.

**Comment by khushishikhu** [comment]
@sayna3311 Please Resolve the merge conflicts

**Comment by sayna3311** [comment]
I am sending a new PR and closing this one.

**Pull request closed without merging**
