### PR TITLE
FAQs in navbar

### LINKED ISSUE #334: FAqs section in navbar
## Is your feature request related to a problem? Please describe.
There should be a section in navbar FAqs for the period beginner girls and for the others too.

### PR DESCRIPTION
**Pull request by kumarishalini6**
#### Description
fixes #334 

This is my 2nd PR on this issue because of failing deploying.

### CODE REVIEW

**Comment by kumarishalini6** [comment]
@khushishikhu please merge this PR . i want to work on other issue

**Comment by kumarishalini6** [comment]
When my PR got merged??

**Comment by khushishikhu** [comment]
@kumarishalini6 I see that your PR has so many errors when I run `yarn run build` that shows why the deployment is failing some of them I have corrected. Rest try to correct them.

**Comment by kumarishalini6** [comment]
Can you please tell me how can the error visible to me because when I run yarn run build it shows false but where I don't understand

**Comment by kumarishalini6** [comment]
@khushishikhu  please merge my PR. The GSSoC'21 is about to end

**Pull request merged**
