### PR TITLE
overlapping in about us solved

### PR DESCRIPTION
**Pull request by Castella1313**
#188 issue solved

this is how it looks now - 

Screenshot 2021-04-09 at 11 17 55 AM

### CODE REVIEW

**Comment by Castella1313** [comment]
@khushishikhu @Aaishpra May you please review my PR?

**Comment by khushishikhu** [comment]
@Castella1313 It looks okay to me, once i test this PR I will merge this

**Comment by Castella1313** [comment]
@khushishikhu Any updates?

**Review by Aaishpra — CHANGES_REQUESTED** [review]
Remove this i don't think there is use of it.

**Comment by Castella1313** [comment]
@Aaishpra done

**Comment by Castella1313** [comment]
@Aaishpra @khushishikhu Can you please check it now!!

**Comment by khushishikhu** [comment]
@Castella1313 you don't need to delete the whole file. But just have to remove the changes that were in package-lock.json and yarn.lock And this is the reason we have got merge conflict. Please solve the merge conflict. I have tested the PR and it works fine

**Comment by Aaishpra** [comment]
Hi @Castella1313 i think you got a bit confused what i meant by removing the files, so basically you didn't had to commit these files where you didn't make any changes for this PR. Since you completely deleted the files from your fork instead of removing it from the commits this has caused a little trouble with this PR, if we merge this PR of yours the package.json and other files will also get deleted from the master/ main branch of the project.

**Comment by Castella1313** [comment]
@Aaishpra Can you please check it now?


Also, Can you please tell me after making changes, this is what I do
git add .
git commit -m "anything"
git push origin branch name



You were talking about not committing the files which I haven't changed, how I should be doing that?

**Comment by Aaishpra** [comment]
Hi @Castella1313 `git add . ` Is not a good command to be used when you are committing a small number of files and there are some files which have changes auto-generated (means not meant to be committed) although i could not understand why there are changes in package.json and other similar files as you didn't add any new package to the project, my best advice would be just do git status after you are done with the changes and git add file_name one by one and after that commit them. As per removing the files you can follow this tutorial https://devconnected.com/how-to-remove-files-from-git-commit/ but if it doesn't works for you just submit a new PR by copy pasting the changes from here to the new PR.

**Pull request closed without merging**
