### PR TITLE
added prettier for code formatting

### LINKED ISSUE #220: Add prettier for code formatting
Add prettier so code should be formatted
More info: https://prettier.io/docs/en/install.html

### PR DESCRIPTION
**Pull request by gnikita432**
#### Description
Issue FIXES #220 

#### Describe the changes you've made
I have added prettier for code formatting and also formatted all the files through prettier

#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)

NA

#### Checklist

- [ ] I have added my name in the contributors list at the end of README.md file.
- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.
- [ ] The title of my pull request is a short description of the requested changes.
- [x] Open Source Program names(OPTIONAL: If you participated in any open-source program then please mention the program name here)GSSOC

### CODE REVIEW

**Review by Aaishpra — APPROVED** [review]
LGTM 💯  Good work

**Comment by Aaishpra** [comment]
Just remove the merge conflicts @gnikita432 and i will merge this asap

**Comment by gnikita432** [comment]
Sorry for the inconvenience but actually, after this PR, I was getting some error while running, so I deleted this repo from my GitHub and now I don't have write access and I am unable to solve the conflicts. So can we close this pull request and I will open a new PR? will it be fine?

**Comment by K-Kumar-01** [comment]
> Sorry for the inconvenience but actually, after this PR, I was getting some error while running, so I deleted this repo from my GitHub and now I don't have write access and I am unable to solve the conflicts. So can we close this pull request and I will open a new PR for the same. will it be fine?

@gnikita432 
Yeah, it is fine. Though the PR would need some update. When you open the new PR can you also set up ESLint configuration also in it.
The details of the issue: #223

**Comment by gnikita432** [comment]
Yes, sure.

**Pull request closed without merging**
