### PR TITLE
page for adding notes

### LINKED ISSUE #49: coding: Create a page for adding notes
I would like to redesign the homepage to be more user-friendly and interactive.
I also would like to add "add note" feature for some important notes the user wants to make.

### PR DESCRIPTION
**Pull request by SandeepKrSuman**
#### Description
FIXES #49 

#### Describe the changes you've made
Added components for notes. Modified the navbar to add link to the notes page. Added new dependency - @material-ui/icons for using icons on the notes page. 

#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
NA

#### Additional context (OPTIONAL)
The project now have a notes page which look and functions like this:-
notes

#### Test plan (OPTIONAL)
Run the project on localhost and navigate to the notes section from the navbar. Add title and body of your note and click on plus sign, note will be saved. Click on delete icon to delete a saved note.

#### Checklist

- [x] My code follows the code style of this project.
- [x] My change does not require a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.
- [x] The title of my pull request is a short description of the requested changes.
- [x] Open Source Program names(OPTIONAL: If you participated in any open-source program then please mention the program name here)

### CODE REVIEW

**Comment by khushishikhu** [comment]
@SandeepKrSuman we really liked your work 💯. Thank you so much for Making this page. Once I test this PR then I will happily merge this. Keep contributing

**Review by khushishikhu — COMMENTED** [review]
@SandeepKrSuman we really liked your work 💯. Thank you so much for Making this page. Once I test this PR then I will happily merge this. Keep contributing

**Comment by khushishikhu** [comment]
@SandeepKrSuman Please solve the merge conflict

**Comment by SandeepKrSuman** [comment]
@khushishikhu I have resolved the conflicts. Have a look.

**Review by khushishikhu — APPROVED** [review]

**Comment by khushishikhu** [comment]
@SandeepKrSuman LGTM!! 🎉 Thank you so much for your contribution. we appreciate your efforts. Keep contributing

**Pull request merged**
