### PR TITLE
Flowpage medium screen

### LINKED ISSUE #255: responsiveness in flow page!
**Describe the bug**
as we discussed for the medium screen. Am making the PR @K-Kumar-01

### PR DESCRIPTION
**Pull request by akshay1027**
#### Description
Issue FIXES #255 

screenshots:  

#### Checklist

- [ ] I have added my name in the contributors list at the end of README.md file.
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [ ] The title of my pull request is a short description of the requested changes.
- [ ] Open Source Program names(OPTIONAL: If you participated in any open-source program then please mention the program name here)

### CODE REVIEW

**Comment by akshay1027** [comment]
@K-Kumar-01 I have done the changes! let me know if you like it! also please add labels as you merge, I have spent some time for this solution as you can see, THank you!

**Comment by K-Kumar-01** [comment]
@akshay1027 Please follow the commit guidelines as I have mentioned earlier also.

**Comment by K-Kumar-01** [comment]
@akshay1027 The deployed preview looks good however, please follow the commit guidelines. Then we can merge this

**Comment by khushishikhu** [comment]
@akshay1027 Here is the [link](https://github.com/Feminine-Divine/periodo/blob/master/.github/CONTRIBUTING.md#commit-conventions) of commit guidelines. Please read this and work accordingly

**Comment by akshay1027** [comment]
Sorry, I will follow this from now! Is it possible to change rhe commits now?

**Comment by K-Kumar-01** [comment]
> Sorry, I will follow this from now! Is it possible to change rhe commits now?

@akshay1027 I will merge the commits as of now but please follow the commit conventions whenever you make a commit. 
Also, please ensure that you do rebase after your pull request is merged. This way the commits saying `Merge pull request ...` won't be shown in your commit

**Comment by akshay1027** [comment]
Can you please add labels ? @K-Kumar-01, I spent time to make it instead of going for a temporary solution

**Pull request merged**
