### PR TITLE
Fixed bug in mobile view for wanna rate yourself page

### LINKED ISSUE #271: bug in wanna rate yourself page
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

image
I would like to solve this issue

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

### PR DESCRIPTION
**Pull request by gnikita432**
#### Description
Issue FIXES #271 

#### Describe the changes you've made

I have fixed the bug in mobile view for wanna rate yourself page and also their was some error in the flow.js file I have resolved that too.

before
image

now
image

#### Checklist

- [ ] I have added my name in the contributors list at the end of README.md file.
- [x ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x ] All new and existing tests passed.
- [ x] The title of my pull request is a short description of the requested changes.
- [ x] Open Source Program names(OPTIONAL: If you participated in any open-source program then please mention the program name here)

### CODE REVIEW

**Review by Aaishpra — APPROVED** [review]
LGTM

**Comment by gnikita432** [comment]
Hey @Aaishpra Thank you for merging the PR, Can you please add level  and gssoc tag also.

**Comment by Aaishpra** [comment]
Added

**Comment by gnikita432** [comment]
Thank you

**Pull request merged**
