### PR TITLE
Opaque background. #148 

### PR DESCRIPTION
**Pull request by AakankshaKamal**
Issue : Opaque background. #148 
To improve the readability ,
Changes made are following in gynae form page:
Screenshot 2021-04-13 184156
Screenshot 2021-04-13 184224

### CODE REVIEW

**Comment by khushishikhu** [comment]
@AakankshaKamal can you please update your branch and remove the merge conflicts

**Comment by AakankshaKamal** [comment]
@khushishikhu Done.

**Comment by Aaishpra** [comment]
Looks like some mess has been created here as I see commits from other contributors in the PR. It would create problem if I merge this PR.
@AakankshaKamal would you mind submitting a new PR for the same?

**Comment by Aaishpra** [comment]
And I don't like the red colour, can you change it to some thing like lavender.
Ok I found the perfect colour for this  Check out : https://www.eggradients.com/color/pink-lavender
#FABED2 is the hex i think

**Comment by AakankshaKamal** [comment]
Ok Sure I ll make the changes and make a new PR.

**Comment by Aaishpra** [comment]
And I don't like the red colour, can you change it to some thing like lavender.
Ok I found the perfect colour for this  Check out : https://www.eggradients.com/color/pink-lavender
#FABED2 is the hex i think

**Pull request closed without merging**
