### PR TITLE
Modified 'click to chat' button

### LINKED ISSUE #173: In home page, click to chat button design can be changed
**Describe the bug**
In the home page, click to chat button design can be changed to make it look more professional.

### PR DESCRIPTION
**Pull request by Fpj-11**
#### Description
Added some hover effect to the 'click to chat' button
Issue FIXES #173 

#### Describe the changes you've made

Added a shadow effect to the 'click to chat' button on hover. 

#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)

NA

#### Checklist

- [ ] I have added my name in the contributors list at the end of README.md file.
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [x] The title of my pull request is a short description of the requested changes.
- [x] Open Source Program names(GirlScript Summer Of Code)

### CODE REVIEW

**Comment by khushishikhu** [comment]
@Fpj-11 I think you made this PR in a wrong way. Because this doesn't requires changes in all the files of the project. Please look into this issue

**Comment by Fpj-11** [comment]
I had made the changes in chatbot.js file and it's css file only

**Comment by Aaishpra** [comment]
Update your fork and create a new branch then send a new PR

**Comment by Aaishpra** [comment]
Btw what's better in this button the previous ome offered hover effect as well as better colour

**Comment by Fpj-11** [comment]
In my opinion, the previous gradient on hover was not looking good

**Pull request closed without merging**
