### PR TITLE
Create a splash screen

### LINKED ISSUE #80: coding: Create a splash screen
**Describe the bug**
Create and design a splash screen for the project whenever we open the website.

**Additional context**
Approval of two mentors needed

### PR DESCRIPTION
**Pull request by mdPial**
#### Description
Issue FIXES #80 

#### Describe the changes you've made

I have used 

- open Source images to avoid any kind of copyright issues.
- google font to avoid any kind of copyright issues.
- svg images so that in any kind of big or small screen it preserve its quality
- pure CSS to make the text animation so that page won't become heavy to load.
- dynamic value to adjust UI according to the screen

I have made also responsive.

As @khushishikhu told to change the background image with the coordination of my splash screen I have set new background also. 

#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)

Currently navbar is not responsive so background image also not showing properly in mobile view.
#### Additional context (OPTIONAL)

Here are the views of different size screen. Some of them is not in 100% zoom.
To get full screen view:
**Full HD (1920x1080 px)** https://j.gifs.com/P7RXX1.gif
**iPhone X (375x812 px)** https://j.gifs.com/XL3mj5.gif
**Laptop (1366x768 px)** https://j.gifs.com/p8GrOp.gif
**iPad Pro (1024x1366 px)** https://j.gifs.com/P7RXX1.gif

monitor
mobile
laptop
ipad
#### Checklist

- [ ] I have added my name in the contributors list at the end of README.md file.
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.
- [x] The title of my pull request is a short description of the requested changes.
- [x] GSSoC'21 (OPTIONAL: If you participated in any open-source program then please mention the program name here)

### CODE REVIEW

**Comment by khushishikhu** [comment]
@mdPial wow!!! You did amazing 😍 Thank you so much for making this , I'll just need to test this PR once if found no issues I will be happy to merge this.

**Review by khushishikhu — COMMENTED** [review]
@mdPial wow!!! You did amazing 😍 Thank you so much for making this , I'll just need to test this PR once if found no issues I will be happy to merge this

**Review by khushishikhu — APPROVED** [review]
@mdPial  LGTM!! 💯  Thank you so much for your contribution.

**Comment by mdPial** [comment]
My pleasure 😄

**Pull request merged**
