### PR TITLE
added nearby hospital lists in React and added new features

### LINKED ISSUE #158: Nearby hospitals List
## Is your feature request related to a problem? Please describe.
Sometimes there may be an emergency case where they need to go to a hospital, or for general treatment.

## Describe the solution you'd like
We can include an option to locate the nearby hospital and could also provide directions for it.

### PR DESCRIPTION
**Pull request by subhangi2731**
#### Description

Added hospitals list and new features in React.js setting the location data

Issue FIXES #158 

#### Describe the changes you've made

Setting the location data and importing the json data of the location of different cities by enabling map api key and modified the googlemap.js in react and imported styles and also added feature of adding nearby hospitals

#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
NA

#### Checklist

- [x] I have added my name in the contributors list at the end of README.md file.
- [x ] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.
- [x] The title of my pull request is a short description of the requested changes.
- [x] Open Source Program names(OPTIONAL: If you participated in any open-source program then please mention the program name here)

### CODE REVIEW

**Comment by subhangi2731** [comment]
@khushishikhu please review and merge my pr

**Comment by khushishikhu** [comment]
@subhangi2731 Which kind of API do we need to add to access can you please elaborate so that I can add that

**Comment by subhangi2731** [comment]
@khushishikhu I have used maps geocoding API which is the process of converting addresses into geographic coordinates which we use to place markers on a map, or position the map and also we use the Geocoding API to find the address for a given place ID. It provides a direct way to access these services via an HTTP request

**Comment by subhangi2731** [comment]
@khushishikhu please merge my pr

**Review by khushishikhu — APPROVED** [review]
@subhangi2731 LGTM!!

**Pull request merged**
