### PR TITLE
social media icons

### PR DESCRIPTION
**Pull request by kumarishalini6**
#295
I have made social media icons in the home page with some hover effects and animations.

https://user-images.githubusercontent.com/69043944/118388450-087af400-b5d1-11eb-9baa-85f9b8fa096d.mp4

### CODE REVIEW

**Comment by kumarishalini6** [comment]
@Aaishpra  please review my PR and can you tell me **why all checks are failed**

**Comment by khushishikhu** [comment]
@kumarishalini6 Please update your branch. Maybe the failing problem will solve itself

**Comment by kumarishalini6** [comment]
Can you please tell me how can I update branch

**Comment by Aaishpra** [comment]
> Can you please tell me how can I update branch

The best way https://stackoverflow.com/questions/7244321/how-do-i-update-or-sync-a-forked-repository-on-github
 The easy way
https://www.google.com/url?sa=t&source=web&rct=j&url=https://medium.com/%40sahoosunilkumar/how-to-update-a-fork-in-git-95a7daadc14e&ved=2ahUKEwjj6c_q0M7wAhVaWysKHf2DBB4QFjACegQIAxAF&usg=AOvVaw0JXDx97lrlDGLPeIv6M2Qt
Implement whatever works for you and another thing can you add the contents of these files in other files instead of creating new files just for social icons

**Comment by kumarishalini6** [comment]
ok

**Comment by kumarishalini6** [comment]
@Aaishpra 
"can you add the contents of these files in other files instead of creating new files just for social icons"
I am getting your point what exactly i have to do?

**Comment by Aaishpra** [comment]
Uhmm like add the code for social media icons somewhere else in the existing files, rather than just creating new files. Do you get it now?

**Comment by kumarishalini6** [comment]
ok give me 5 min

**Comment by kumarishalini6** [comment]
Done

**Comment by kumarishalini6** [comment]
@Aaishpra please check this issue I have done all the changes and update the branch also

**Review by khushishikhu — APPROVED** [review]

**Pull request merged**
