### PR TITLE
Fixes:Clean the code #282

### LINKED ISSUE #282: Clean the code.
**Describe the bug**

- Due to a lot of contributions, the code is messy right now. For example improper indentation, unesseccary spaces/tabs, lack of comments to explain the code and extra commented code.
- All this makes it difficult for beginner contributors to understand the code.
- So the code should be cleaned.

**Additional context**

Please assign it under `Gssoc21`.
@khushishikhu @Aaishpra

### PR DESCRIPTION
**Pull request by Shivangi-ch**
#### Description
Issue FIXES #282

#### Describe the changes you've made

 -improper indentation
 -unesseccary spaces/tabs
 -lack of comments to explain the code and 
  -Removed extra commented code.
#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)

NA

#### Checklist

- [x] I have added my name in the contributors list at the end of README.md file.
- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.
- [x] The title of my pull request is a short description of the requested changes.
- [x] Open Source Program names(OPTIONAL: If you participated in any open-source program then please mention the program name here)

### CODE REVIEW

**Comment by Shivangi-ch** [comment]
@Aaishpra Please review.

**Review by khushishikhu — APPROVED** [review]
@Shivangi-ch LGTM!!. Great work

**Comment by khushishikhu** [comment]
@Shivangi-ch please resolve the merge conflict so that I can merge it

**Comment by Shivangi-ch** [comment]
@khushishikhu @Aaishpra You can merge now, I have resolved the confilcts.

**Pull request merged**
