### PR TITLE
Third-party authentication added using nextjs-auth0 Issue #16

### LINKED ISSUE #16: coding: Add Third-Party Authentication
## Description
Add the third party authentication to login in the app through Google account/ Facebook account. And add the sensitive information in environment variables ( .env file)

### PR DESCRIPTION
**Pull request by nishihere19**
#### Description
Issue FIXES #16

#### Describe the changes you've made

I've added Login/Logout feature with third party authentication(Google & Facebook) and added credentials in .env file.

#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)

No.

#### Additional context (OPTIONAL)

Screenshot from 2021-03-10 22-52-48
Screenshot from 2021-03-10 22-53-21
Screenshot from 2021-03-10 22-53-31

#### Checklist

- [ ] I have added my name in the contributors list at the end of README.md file.
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [x] The title of my pull request is a short description of the requested changes.
- [x] Open Source Program names(OPTIONAL: If you participated in any open-source program then please mention the program name here)
- [x] Gssoc

### CODE REVIEW

**Comment by nishihere19** [comment]
KIndly Let me know if any changes are required. Also, kindly add the gssoc label in the PR. Thank you.

**Comment by nishihere19** [comment]
I ran into this error while I was trying to pull code and build the app again. Kindly guide me in this @khushishikhu  
Screenshot from 2021-03-23 00-28-38

**Comment by khushishikhu** [comment]
@nishihere19  Instead of running `npm run-script build` you should run `npm run dev` I am hoping that this will solve your issue. If anything happens again feel free to ask us

**Comment by nishihere19** [comment]
I have resolved all the conflicts and updated the code. Kindly let me know if any changes are required.

**Review by khushishikhu — COMMENTED** [review]
@nishihere19 I have tested this PR but found some errors can you please look into that why are they throwing these errors? and for any help please feel free to ask, we will help you out in all possible ways
image

**Comment by nishihere19** [comment]
Hi, I have resolved the issue due to auth0.js in build. Kindly refer to the screenshot below and let me know if any more changes are required.
Screenshot from 2021-03-24 10-46-43

**Comment by khushishikhu** [comment]
@nishihere19 have you tested your PR to yourself ? because I am running `npm run dev` but still throwing some errors when I am testing . Please look again and let me know if you need any help

**Comment by nishihere19** [comment]
I my machine it shows no errors and runs dev and builds successfully in one go.

**Comment by khushishikhu** [comment]
@nishihere19 can you please send me the screenshot of how it is working on website.

**Comment by nishihere19** [comment]
You mean on localhost?

**Comment by khushishikhu** [comment]
> You mean on localhost?
yes

**Comment by khushishikhu** [comment]
> You mean on localhost?

yes

**Comment by nishihere19** [comment]
Screenshot from 2021-03-25 15-12-30
Screenshot from 2021-03-25 15-12-32
Screenshot from 2021-03-25 15-12-40

**Review by khushishikhu — APPROVED** [review]
@nishihere19 LGTM 🎉 💯 . Thank you so much for your contribution. We really appriciate your efforts. Keep contributing.

**Comment by nishihere19** [comment]
Thanks a lot!

**Pull request merged**
