### PR TITLE
Added footer

### LINKED ISSUE #30: Feat: Creating a decent footer for website.
Hi @khushishikhu ,
A decent footer can  be added to the website containing links to the github source code, and organization name.
As a part of gssoc'21 I would like to work on it.

### PR DESCRIPTION
**Pull request by WaderManasi**
#### Description
Issue FIXES #30

#### Describe the changes you've made

Added footer to the website
#### Checklist

- [] I have added my name in the contributors list at the end of README.md file.
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [ ] The title of my pull request is a short description of the requested changes.
- [x] Open Source Program names(OPTIONAL: If you participated in any open-source program then please mention the program name here)  - **GSSOC'21**

### CODE REVIEW

**Comment by khushishikhu** [comment]
@WaderManasi you can add a scroll bar also if the footer is overlapping with the background image.

**Comment by WaderManasi** [comment]
Sure, and is it ok with the colors used in footer?

**Comment by WaderManasi** [comment]
Actually the site is not responsive, otherwise the footer would automatically have been placed below the background wallpaper. But I will try again and then create another PR.

**Comment by khushishikhu** [comment]
@WaderManasi footer is completely fine. And you don't need to create another PR for placing footer below the background wallpaper just make changes in this PR only

**Comment by WaderManasi** [comment]
Okay..

**Comment by WaderManasi** [comment]
Just check once...
screencapture-localhost-3000-2021-03-12-11_39_15

**Comment by WaderManasi** [comment]
Updated the PR with latest code!

**Comment by Aaishpra** [comment]
@WaderManasi can you add contact form at the end in foooter instead of adding tips and home again

**Comment by Aaishpra** [comment]
And i am not a fan of that colourful part added below the navbar can you remove it and just keep the background image.

**Comment by WaderManasi** [comment]
I will add contact us link instead of tips and home but for that, first contact us page should be created. This issue is created for adding footer. Shall I create new issue for creating a contact page.?

**Comment by WaderManasi** [comment]
That contact us page will be consisting of styled contact form.

**Comment by Aaishpra** [comment]
Okay open a new issue for that but send both work in this PR.
Don't worry about the scores we will assign you marks for both the issues

**Comment by WaderManasi** [comment]
Okay no problem.

**Comment by WaderManasi** [comment]
Do you any suggestions about what extra should be added in contact form fields ?.

**Comment by Aaishpra** [comment]
Name, Email, Your Feedback

**Comment by WaderManasi** [comment]
Got it @Aaishpra

**Comment by WaderManasi** [comment]
I have create the new issue regarding this..kindly assign it to me.
Thank you

**Comment by Aaishpra** [comment]
Conflicts are still remaining resolve them

**Pull request closed without merging**
