### PR TITLE
Issue #3

### LINKED ISSUE #3: Feat: Modify the "Tap Here" button
## Description
Modify the Tap Here button of the homepage

### PR DESCRIPTION
**Pull request by Shwetang550**
#### Description
Issue FIXES #3

#### Describe the changes you've made

Updated the css styles of "Tap Here" Button

"Tap Here" Button Modification
- Border Radius updated
- Hover Effect added

https://user-images.githubusercontent.com/53322975/110679654-b6e37100-81fd-11eb-8672-ebedc8b85997.mp4

### CODE REVIEW

**Comment by khushishikhu** [comment]
@Shwetang550 Thank you so much for this. I liked this animation . Keep contributing!!

**Comment by Shwetang550** [comment]
Thank You @khushishikhu 😄

**Comment by khushishikhu** [comment]
@Shwetang550 Pease resolve the Merge conflict

**Comment by Shwetang550** [comment]
Hey @khushishikhu... Fixed the merge conficts ✔️

**Pull request merged**
