### PR TITLE
navigation drawer added

### LINKED ISSUE #261: Change the navbar into sidebar or navigation drawer
## Is your feature request related to a problem? Please describe.

The current navbar is bulky and not very geat looking
## Describe the solution you'd like

Change the navbar into a sidebar or more commonly navigation drawer.
## Additional context

Use material-UI for styling 
Checkout:
https://material-ui.com/components/drawers/
https://stackoverflow.com/questions/39865799/making-sidebar-with-material-ui

### PR DESCRIPTION
**Pull request by subhangi2731**
#### Description
Navigation drawers provide access to destinations in your app.Navigation drawers provide access to destinations and app functionality, such as switching accounts. They can either be permanently on-screen or controlled by a navigation menu icon.
Navigation drawers are recommended for:Apps with five or more top-level destinations, Apps with two or more levels of navigation hierarchy and Quick navigation between unrelated destinations

Issue FIXES #261 

#### Describe the changes you've made

I have made a new file navbar.component.style.js and modified navbar.js and started.module.css I have changed the navbar to sidebar or navigation drawer

#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
NA

#### Checklist

- [x] I have added my name in the contributors list at the end of README.md file.
- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.
- [x] The title of my pull request is a short description of the requested changes.
- [x] Open Source Program name(I had participated in NJACK Winter of Code, KWOC and SWOC
Screenshot from 2021-05-14 11-46-27
)

### CODE REVIEW

**Comment by subhangi2731** [comment]
@Aaishpra please review and merge my pr

**Comment by Aaishpra** [comment]
Can you add videos/gifs showing your results.

**Comment by Aaishpra** [comment]
and no need to add code screenshots, I can see the code in the file changes

**Comment by subhangi2731** [comment]
@Aaishpra okay sure i will add it in some time

**Comment by subhangi2731** [comment]
https://user-images.githubusercontent.com/53938490/118277801-cbd2ce00-b4e6-11eb-9ff3-701afbfc25ea.mp4

**Comment by subhangi2731** [comment]
@Aaishpra here it is please see and merge

**Comment by Aaishpra** [comment]
Great work here @subhangi2731 can you change that blue colour in the navbar to black

**Comment by subhangi2731** [comment]
@Aaishpra thank u sure I will change it

**Comment by subhangi2731** [comment]
@Aaishpra I have changed the colour to black of navbar please merge

**Comment by subhangi2731** [comment]
@khushishikhu please review and merge

**Review by khushishikhu — APPROVED** [review]
@subhangi2731 Thank you so much for this. LGTM!! 💯

**Comment by subhangi2731** [comment]
@khushishikhu thank u so much

**Pull request merged**
