### PR TITLE
about us overlapping fixed

### LINKED ISSUE #188: About us Page fixation
About us component is overlapping with the Navbar

Screenshot 2021-04-08 at 9 09 02 PM

### PR DESCRIPTION
**Pull request by Castella1313**
#188 fixed

### CODE REVIEW

**Comment by Castella1313** [comment]
@Aaishpra Can you please check it now!

**Comment by Aaishpra** [comment]
@khushishikhu can you test it?

**Comment by khushishikhu** [comment]
@Aaishpra yes will test it by EOD

**Comment by Castella1313** [comment]
@Aaishpra any updates?

**Review by Aaishpra — APPROVED** [review]
Tested and it works perfectly fine 💯 
Good work and congrats on merging your first PR with Periodo.
Keep contributing 💪🏻

**Pull request merged**
